[0m16:21:28.101271 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x112719d50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x112792510>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x112792d50>]}


============================== 16:21:28.105356 | 2e342c0f-4c64-483a-a0cf-5c77edd75395 ==============================
[0m16:21:28.105356 [info ] [MainThread]: Running with dbt=1.9.2
[0m16:21:28.105821 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/Users/jdemlow/.dbt', 'fail_fast': 'False', 'debug': 'False', 'log_path': 'logs', 'warn_error': 'None', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'log_format': 'default', 'invocation_command': 'dbt run-operation run_query --args {"query": "create database if not exists raw"}', 'introspect': 'True', 'static_parser': 'True', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m16:21:28.106254 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/jdemlow/github/dbt-dynamic-tables-snowflake/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m16:21:28.108772 [debug] [MainThread]: Resource report: {"command_name": "run-operation", "command_success": false, "command_wall_clock_time": 0.096242, "process_in_blocks": "0", "process_kernel_time": 0.19773, "process_mem_max_rss": "97148928", "process_out_blocks": "0", "process_user_time": 0.731512}
[0m16:21:28.109275 [debug] [MainThread]: Command `dbt run-operation` failed at 16:21:28.109045 after 0.10 seconds
[0m16:21:28.109591 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10e3bb010>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x112719690>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x112719d50>]}
[0m16:21:28.109860 [debug] [MainThread]: Flushing usage events
[0m16:21:29.211061 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m16:21:30.366026 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10fc65e10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10fcbc1d0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10fcbddd0>]}


============================== 16:21:30.369806 | 86b19b44-5b7e-4580-aec5-fb08f0849215 ==============================
[0m16:21:30.369806 [info ] [MainThread]: Running with dbt=1.9.2
[0m16:21:30.370319 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'profiles_dir': '/Users/jdemlow/.dbt', 'log_path': 'logs', 'debug': 'False', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'log_format': 'default', 'static_parser': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'target_path': 'None', 'invocation_command': 'dbt run-operation run_query --args {"query": "create schema if not exists raw.sales"}', 'send_anonymous_usage_stats': 'True'}
[0m16:21:30.370776 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/jdemlow/github/dbt-dynamic-tables-snowflake/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m16:21:30.372769 [debug] [MainThread]: Resource report: {"command_name": "run-operation", "command_success": false, "command_wall_clock_time": 0.07978075, "process_in_blocks": "0", "process_kernel_time": 0.144854, "process_mem_max_rss": "98045952", "process_out_blocks": "0", "process_user_time": 0.735759}
[0m16:21:30.373257 [debug] [MainThread]: Command `dbt run-operation` failed at 16:21:30.373037 after 0.08 seconds
[0m16:21:30.373584 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10fcbdd90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10b89f010>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10b89e710>]}
[0m16:21:30.373849 [debug] [MainThread]: Flushing usage events
[0m16:21:31.577278 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m16:21:32.712108 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10e65e2d0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10e6d64d0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10e6d6d10>]}


============================== 16:21:32.715791 | 83944125-e2f3-4eef-8aad-905677d8ac9a ==============================
[0m16:21:32.715791 [info ] [MainThread]: Running with dbt=1.9.2
[0m16:21:32.716273 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'profiles_dir': '/Users/jdemlow/.dbt', 'log_path': 'logs', 'fail_fast': 'False', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'static_parser': 'True', 'introspect': 'True', 'invocation_command': 'dbt run-operation generate_test_orders --args {"days_back": 30, "orders_per_day": 100, "drop_existing": true}', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m16:21:32.716710 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/jdemlow/github/dbt-dynamic-tables-snowflake/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m16:21:32.718797 [debug] [MainThread]: Resource report: {"command_name": "run-operation", "command_success": false, "command_wall_clock_time": 0.081770085, "process_in_blocks": "0", "process_kernel_time": 0.150248, "process_mem_max_rss": "98000896", "process_out_blocks": "0", "process_user_time": 0.734342}
[0m16:21:32.719319 [debug] [MainThread]: Command `dbt run-operation` failed at 16:21:32.719096 after 0.08 seconds
[0m16:21:32.719665 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10a29ef10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10e365410>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10e65a390>]}
[0m16:21:32.719947 [debug] [MainThread]: Flushing usage events
[0m16:21:33.304882 [debug] [MainThread]: An error was encountered while trying to flush usage events
